tableau:
  server: "https://public.tableau.com/"
  project: "Superstore_1057"
  view: "Overview"
  changes:
    filters: True
    marks: True
    parameters: True
wordsmith:
  api_key: '*'
  project_slug: 'project'
  template_slug: 'template'
html:
  title: "SuperStore Sample"
  file: "table.html"
dev: False
